module.exports = {
    ERROR_STATUS : 'ERROR',
    SUCCESS_STATUS : 'OK',
    SUCCESS_CODE : 200,
    CREATED_CODE : 201,
    SUCCESS_NO_CONTENT : 204,
    BAD_REQUEST_CODE : 400,
    UNAUTHORIZED_CODE : 401,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR_CODE : 500
};