// ACCIONES CLIENTE
export const OBTENER_CLIENTES   = 'OBTENER_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const VALIDAR_CLIENTE = 'VALIDAR_CLIENTE';
export const CLIENTE_ACTUAL = 'CLIENTE_ACTUAL';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';
export const ERROR_ELIMINAR_CLIENTE = 'ERROR_ELIMINAR_CLIENTE';
export const EDITAR_CLIENTE = 'EDITAR_CLIENTE';
export const LIMPIAR_CLIENTE_ACTUAL = 'LIMPIAR_CLIENTE_ACTUAL'
export const AGREGAR_CLASE_CLIENTE = 'AGREGAR_CLASE_CLIENTE';
export const OBTENER_CLASES_CLIENTE = 'OBTENER_CLASES_CLIENTE';
export const LIMPIAR_CLASES_CLIENTE = 'LIMPIAR_CLASE_CLIENTE';
export const ELIMINAR_CLASE_CLIENTE = 'ELIMINAR_CLASE_CLIENTE';

// PERSONAL
export const OBTENER_PERSONAL = 'OBTENER_PERSONAL';
export const AGREGAR_PERSONAL = 'AGREGAR_PERSONAL';
export const VALIDAR_PERSONAL = 'VALIDAR_PERSONAL';
export const PERSONAL_ACTUAL = 'PERSONAL_ACTUAL';
export const EDITAR_PERSONAL = 'EDITAR_PERSONAL';
export const ELIMINAR_PERSONAL = 'ELIMINAR_PERSONAL';
export const OBTENER_CLASES_ENTRENADOR = 'OBTENER_CLASES_ENTRENADOR';
export const OBTENER_ACTIVIDADES_ENTRENADOR = 'OBTENER_ACTIVIDADES_ENTRENADOR';
export const LIMPIAR_CLASES_ENTRENADOR = 'LIMPIAR_CLASES_ENTRENADOR';
export const LIMPIAR_ACTIVIDADES_ENTRENADOR = 'LIMPIAR_ACTIVIDADES_ENTRENADOR';
export const LIMPIAR_PERSONAL_ACTUAL = 'LIMPIAR_PERSONAL_ACTUAL';

// Actividades
export const OBTENER_ACTIVIDADES = 'OBTENER_ACTIVIDADES';
export const ACTIVIDAD_ACTUAL = 'ACTIVIDAD_ACTUAL';
export const OBTENER_CLASES_ACTIVIDAD = 'OBTENER_CLASES_ACTIVIDAD';
export const LIMPIAR_CLASES_ACTIVIDAD = 'LIMPIAR_CLASES_ACTIVIDAD';


// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
